Exporting default middlewares to a new folder and adding json support…
luizguilhermesj/generic-rest-api pull request #3
Opened 2018-02-21 21:52 UTC by JoaoBGusmao

… on 'where'

2018-02-22 17:26 UTC, luizguilhermesj requested changes
Missing `express-routes.js` changes, that will be needed for this to work.

Also need to update the `readme` explaining how to use the new functionality and to update the package json with the new version as a major release (3.1.0)

2018-02-22 17:26 UTC, luizguilhermesj commented on middlewares/sequelize-options.js
> +
this two `if` statments could be isolated methods, and the `delete` operation is now useful when there is a `req.query.where`

2018-02-22 17:26 UTC, luizguilhermesj commented on middlewares/sequelize-options.js
> +    }
could it be a method that returns the options abstracting this logic?

2018-02-22 20:49 UTC, JoaoBGusmao commented
changes done @luizguilhermesj

2018-02-23 14:48 UTC, luizguilhermesj approved these changes

2018-02-23 16:24 UTC, merged